### ISSUE TITLE
Error message when using sampleOccurrences function on the basis of the output list from the convertToPA function

### ISSUE THREAD

**Issue by cmontalvo-mancheno** [Farewe/virtualspecies#10]
Hi Boris!
First of all thanks a lot for this great package!

Using the output list from the convertToPA function, I am trying to sample biased presence points. Yet, I got an error (see first chunk of code in the red rectangle in the attached screenshot). **Could you please advise on what I must change/do to deal with this error?** 

![Error_message_sampleOccurrences_virtualspecie_R](https://user-images.githubusercontent.com/81724937/113806362-7d266b80-97a5-11eb-8ec6-7249a2734f27.jpg)

I was able to circumvallate this error by using the pa.raster found in the output list (please see chunk of code in the green rectangle). Yet, I would like to set the correct.by.suitability to TRUE, but my solution produces another error (please see chunk of code in the blue rectangle).

It seems to me that I cannot set correct.by.suitability to TRUE because the sampleOccurrences function is looking for the suitability raster stored in the output list (please see black rectangle), which I cannot provide unless I use the output list generated by the convertToPA function.

I thank you for your time!

Cheers,

Cristian

**Comment by Farewe** [comment]
Hello Cristian,

Could you save your virtualspecies object (`pres_absence_sp.A.3`) with `saveRDS`, zip the saved file, and attach it here please?
It will be easier for me to investigate the issue. 

Cheers
Boris

**Comment by cmontalvo-mancheno** [comment]
Hi Boris!
Thanks for your prompt response and time. Attached you will find the file you requested.
Cheers,
Cristian
[pres_absence_sp.A.3.zip](https://github.com/Farewe/virtualspecies/files/6275736/pres_absence_sp.A.3.zip)

**Comment by Farewe** [comment]
Hey Cristian, I had time to look  at it, but it appears that the object you sent is not a true virtualspecies object, because it does not have the correct class. It seems to be a list you created or modified based on the virtualspecies functions. 

To make the function work, you need to indicate to it that your object is supposed to be a virtualspecies object. You can do it with `append(class(<object>), "virtualspecies")`. This is a workaround though, only to make the sampling of occurrences work, because some slots of the virtualspecies will be missing. It would be best to have a proper virtualspecies object in the first place, and modify its slots to fit your needs.

The following example code worked for me:

```
a <- readRDS("d:/r/data/pres_absence_sp.A.3.rds")
class(a) <- append(class(a), "virtualspecies")

sampleOccurrences(a, n = 100, correct.by.suitability = TRUE)
```

**Comment by cmontalvo-mancheno** [comment]
Hi Boris!
I apologize it took me a while to respond. Your solution worked for me too.
Thanks for your support and time!
Cristian

**Comment by cmontalvo-mancheno** [comment]
Hi Boris!
I apologize it took me a while to respond. Your solution worked for me too.
Thanks for your support and time!
Cristian
