### ISSUE TITLE
Plans to change dependencies from `raster` to `terra` ?

### ISSUE THREAD

**Issue by Martin-Jung** [Farewe/virtualspecies#12]
The `raster` and other packages depending on `rgdal` will [retire from CRAN this October 2023](https://r-spatial.org/r/2022/04/12/evolution.html) at which point this package might also get taken of from CRAN owing to the dependency on `raster`. 

Are there any plans to convert the functionalities from `raster` to `terra`? This can also substantially increase the speed...

**Comment by Farewe** [comment]
Dear Martin,

Yes, I had this on my to-do list for June but unfortunately I did not have enough time to do it. Maybe I'll be able to find time on my holidays to do this, this summer. 

I think the changes are straightforward to do, they should not need too much time and energy, but I still need multiple days of work to ensure that everything runs properly without bugs, which is why i have not had the time to do it until now.

Cheers
Boris

**Comment by Farewe** [comment]
I have just pushed an update of the package to shift to terra, and I submitted it to CRAN as well, it should be on its way soon on the CRAN
