### ISSUE TITLE
rescale and rescale.each.response arguments not working.

### ISSUE THREAD

**Issue by jscamac** [Farewe/virtualspecies#6]
Hi Boris,
First great package!

I've been playing around with it and realised that `generateRandomSp()` has two arguments `rescale` and `rescale.each.response`. However, when setting these arguments to `FALSE` outputs and responses are still scaled between zero and 1.
Looking at the base code, I've realised that these arguments don't appear to integrated into the code:
https://github.com/Farewe/virtualspecies/blob/master/R/generateRandomSp.R

**Comment by Farewe** [comment]
Hi James,

thanks a lot for your contribution!
This was indeed an omission, thanks for that.

About the conversion into presence-absence, I think it is preferable to adjust the conversion to the raw suitability raster (i.e. adjust alpha/beta), rather than convert the raw suitability raster into 0/1 and then convert it. It would avoid storing two versions of the suitability raster (raw + 0/1), which can be confusing. I will look into that. Please give me feedback on this if it seems inappropriate to you!

**Comment by Farewe** [comment]
I have updated the package with your fix and then modified it to avoid altering the raw version of the suitability raster.
Please see if it works for you this way!

**Comment by jscamac** [comment]
Thanks Boris,
I like the alpha adjustment approach. Much more elegant then my initial approach.
However, you've left some residual code that referred to raw.suitab.raster. I've created a new pull request fixing this issue for you.

**Comment by Farewe** [comment]
Great, thanks!

Don't hesitate to repoen if there is anything else.
